name: Publish to PyPI

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # Required for PyPI trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version-file: ".python-version"
      - run: uv build
      - run: uv publish --trusted-publishing always
